### ISSUE TITLE
Remove developer dependencies from user install

### ISSUE THREAD

**Issue by jontwo** [conda-forge/pytesseract-feedstock#14]
Issue:
When you install pytesseract using conda-forge, packages such as `flake8` and `pytest` are included. These should not be needed for a user install. If you look at the `pytesseract` [project page](https://github.com/madmaze/pytesseract/blob/master/setup.py), the only dependency is `Pillow`.

The following could be moved from the `run` section of `meta.yaml` to the `test` section or removed altogether:
    - flake8
    - pep8-naming
    - flake8-quotes
    - pytest

**Comment by bozhodimitrov** [comment]
Thank you for reporting this @jontwo. This seems to be automatically generated section in `meta.yaml`
